function [coordloc,uloc] = locvalues(coord,con,usol,ndf,nne,ielm,lin_quad,interface)

coordloc = zeros(nne,2);

% read xloc
for i = 1:nne
    coordloc(i,:) = coord(con(ielm,i),:);
end

% read uloc
if (lin_quad == 1)  % four-node elements (and four-node interfaces)

    uloc = [    usol(ndf*con(ielm,1)-1,1);...
                usol(ndf*con(ielm,1)  ,1);...
                usol(ndf*con(ielm,2)-1,1);...
                usol(ndf*con(ielm,2)  ,1);...
                usol(ndf*con(ielm,3)-1,1);...
                usol(ndf*con(ielm,3)  ,1);...
                usol(ndf*con(ielm,4)-1,1);...
                usol(ndf*con(ielm,4)  ,1)];
elseif ( lin_quad == 100 )
    uloc = [    usol(ndf*con(ielm,1)-1,1);...
                usol(ndf*con(ielm,1)  ,1);...
                usol(ndf*con(ielm,2)-1,1);...
                usol(ndf*con(ielm,2)  ,1);...
                usol(ndf*con(ielm,3)-1,1);...
                usol(ndf*con(ielm,3)  ,1)];
else  
    
    if (interface == 0)  % eight-node elements
        
    uloc = [    usol(ndf*con(ielm,1)-1,1);...
                usol(ndf*con(ielm,1)  ,1);...
                usol(ndf*con(ielm,2)-1,1);...
                usol(ndf*con(ielm,2)  ,1);...
                usol(ndf*con(ielm,3)-1,1);...
                usol(ndf*con(ielm,3)  ,1);...
                usol(ndf*con(ielm,4)-1,1);...
                usol(ndf*con(ielm,4)  ,1);...
                usol(ndf*con(ielm,5)-1,1);...
                usol(ndf*con(ielm,5)  ,1);...
                usol(ndf*con(ielm,6)-1,1);...
                usol(ndf*con(ielm,6)  ,1);...
                usol(ndf*con(ielm,7)-1,1);...
                usol(ndf*con(ielm,7)  ,1);...
                usol(ndf*con(ielm,8)-1,1);...
                usol(ndf*con(ielm,8)  ,1)];
            
    else  % six-node interfaces
    
    uloc = [    usol(ndf*con(ielm,1)-1,1);...
                usol(ndf*con(ielm,1)  ,1);...
                usol(ndf*con(ielm,2)-1,1);...
                usol(ndf*con(ielm,2)  ,1);...
                usol(ndf*con(ielm,3)-1,1);...
                usol(ndf*con(ielm,3)  ,1);...
                usol(ndf*con(ielm,4)-1,1);...
                usol(ndf*con(ielm,4)  ,1);...
                usol(ndf*con(ielm,5)-1,1);...
                usol(ndf*con(ielm,5)  ,1);...
                usol(ndf*con(ielm,6)-1,1);...
                usol(ndf*con(ielm,6)  ,1)];    
        
    end
    
end